services:
  - type: web
    name: universal-wallpaper-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://universaldotwallpaper.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html