services:
  # Combined Frontend + Backend Service (since using same domain)
  - type: web
    name: universal-wallpaper
    env: node
    plan: free
    buildCommand: |
      # Install backend dependencies
      npm install
      # Install frontend dependencies and build
      cd frontend && npm install && npm run build && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000