services:
  # Combined Frontend + Backend Service (since using same domain)
  - type: web
    name: universal-wallpaper
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000