services:
  # Frontend Service
  - type: web
    name: universal-wallpaper-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend Service  
  - type: web
    name: universal-wallpaper-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        fromService:
          type: web
          name: universal-wallpaper-frontend
          property: host